/**
 * Auth and onboarding (#251): home page, create workspace, login, sign-up,
 * setup, password reset, invitations, and better-auth's errors. Top-level
 * groups here must not collide with other areas' (the aggregate catalog
 * test checks).
 */
export const authEn = {
  home: {
    title: "Welcome, {name}",
    pageTitle: "Welcome",
    noWorkspace:
      "You are not a member of any workspace yet — create the first one.",
    workspaceName: "Workspace name",
    withDemo: "Add demo data and a sample dashboard",
    withDemoHint: "— generated numbers to explore with; delete them any time.",
    create: "Create workspace",
    newTitle: "New workspace",
    newSubtitle:
      "A workspace has its own dashboards, sources, screens and team.",
  },
  authFields: {
    name: "Name",
    email: "Email",
    password: "Password",
  },
  /** First-run onboarding (#308): the step rail and steps 2 and 3. */
  onboarding: {
    pageTitle: "Get started",
    tagline: "Your first number on a screen in about five minutes.",
    stepsLabel: "Setup steps",
    steps: {
      workspace: "Create your workspace",
      source: "Connect a source",
      screen: "Show it on a screen",
    },
    done: "(done)",
    railNote:
      "Skip any step — demo data keeps your first dashboard from being empty.",
    source: {
      title: "Connect your first source",
      subtitle: "Pick one to start. You can add more later under Sources.",
      choicesLabel: "Sources",
      demoName: "Explore with demo data",
      demoText: "Generated numbers and a sample dashboard",
      demoReady: "Already added to this workspace",
      unavailable: "Not set up on this installation",
      explainOAuth:
        "netrics asks {name} for read-only access. You choose what to sync in the next step, and you can revoke the access at any time: disconnect the source here, or remove netrics in your account at the provider.",
      explainKey:
        "netrics only reads metrics from {name}, with the key you enter in the next step. The key is stored encrypted; deleting the source removes it.",
      explainNone:
        "netrics only reads metrics from {name} and changes nothing there. Delete the source at any time.",
      explainDemo:
        "Demo data is generated by netrics: no account, and no access to anything of yours. Remove it at any time under Sources.",
      skip: "Skip, use demo data",
      continue: "Continue",
      continueWith: "Continue with {name}",
      adding: "Adding demo data…",
      demoFailed:
        "The demo data could not be added. Try again, or connect a source instead.",
    },
    screen: {
      title: "Show it on a screen",
      subtitle:
        "Pair a TV or any browser with this workspace. It shows your dashboard full screen and keeps it up to date.",
      open: "On the TV, open the netrics app (Apple TV) or a browser at {url}.",
      code: "The screen shows a pairing code.",
      enter: "Enter the code under “Connect a TV” and choose the dashboard.",
      askAdmin: "Ask an owner or admin of this workspace to connect a TV.",
      connectTv: "Connect a TV",
      openDashboard: "Open my dashboard",
      connectSource: "Connect a source",
    },
  },
  login: {
    title: "Sign in",
    heading: "Welcome back",
    subtitle: "Your screens are running. Sign in to change what they show.",
    submit: "Sign in",
    pending: "Signing in…",
    forgot: "Forgot password?",
    noAccount: "No account yet? {link}",
    createOne: "Create one",
  },
  signup: {
    title: "Create account",
    subtitle: "Register for netrics",
    submit: "Create account",
    pending: "Creating account…",
    haveAccount: "Already have an account? {link}",
    signIn: "Sign in",
    closedTitle: "Sign-up is closed",
    closedText:
      "Accounts on this installation are created by invitation. Ask an administrator to invite you.",
  },
  setup: {
    title: "Set up netrics",
    subtitle:
      "Create the first account. It becomes the owner of your first workspace.",
    token: "Setup token",
    tokenHint:
      "The setup token is printed in the API log when the installation starts, or set by your operator as NETRICS_SETUP_TOKEN.",
    submit: "Create owner account",
    pending: "Setting up…",
    invalidToken: "The setup token is invalid or was already used.",
  },
  passwordReset: {
    forgotTitle: "Reset password",
    forgotSubtitle: "We email you a link to choose a new password",
    send: "Send reset link",
    sending: "Sending…",
    sent: "If an account exists for that address, we sent a link to reset the password. It is valid for {hours, plural, one {# hour} other {# hours}}.",
    tooManyRequests: "Too many requests. Wait a few minutes and try again.",
    sendFailed: "We could not send the email. Try again later.",
    remembered: "Remembered it? {link}",
    signIn: "Sign in",
    resetTitle: "Choose a new password",
    resetSubtitle: "Set the password for your netrics account",
    invalidLink: "This reset link is invalid or has expired.",
    missingLink: "This page needs the link from the reset email.",
    requestNew: "Request a new link",
    backToSignIn: "Back to sign in",
    newPassword: "New password",
    confirmPassword: "Confirm new password",
    minLengthHint: "At least {count} characters.",
    submit: "Set new password",
    saving: "Saving…",
    done: "Password changed. Other sessions were signed out. {link} with the new password.",
    mismatch: "The passwords do not match.",
  },
  invite: {
    notFoundTitle: "Invitation not found",
    notFoundText:
      "This link is not valid. Check that you copied it completely.",
    title: "Join {workspace}",
    accepted: "This invitation has already been used.",
    revoked: "This invitation was withdrawn. Ask for a new one.",
    expired: "This invitation has expired. Ask for a new one.",
    invitedAs: "You were invited as {role} with {email}.",
    haveAccount: "Already have an account for {email}? {link}",
    signIn: "Sign in",
    wrongAccount:
      "You are signed in as {signedIn}, but this invitation is for {invited}.",
    signOut: "Sign out",
    accept: "Accept invitation",
    joining: "Joining…",
    createAndJoin: "Create account and join",
    creating: "Creating account…",
  },
  /** better-auth's error codes, worded for people. */
  authErrors: {
    invalidCredentials: "That email and password do not match an account.",
    wrongPassword: "The current password is not correct.",
    invalidEmail: "Enter a valid email address.",
    userExists: "An account with this email already exists. Sign in instead.",
    passwordTooShort: "Use at least {count} characters.",
    passwordTooLong: "Use at most {count} characters.",
    signupDisabled: "Sign-up is disabled on this installation.",
    emailNotVerified: "Confirm your email address first.",
    sessionExpired: "Your session has expired — sign in again.",
    invalidToken: "This link is invalid or has expired.",
    tooManyAttempts: "Too many attempts. Wait a few minutes and try again.",
    signInFailed: "Sign-in failed. Try again.",
    signUpFailed: "Sign-up failed. Try again.",
    setupFailed: "Setup failed. Try again.",
    changePasswordFailed: "Could not change the password. Try again.",
    generic: "Something went wrong. Try again.",
  },
} as const;
